version: '3.3'
services:
  mydb:
    image: mariadb
    volumes:
    - vipdb:/var/lib/mysql
    - ./sql:/docker-entrypoint-initdb.d
    environment:
    - MARIADB_ROOT_PASSWORD=secret
  
  tool:
    image: tool
    build: tools
    command: sleep 9999

  web:
    image: web:v8
    build: .
    ports:
    - 80
    environment:
    - TITLE=Friday
    - COLOR=hotpink

volumes:
  vipdb: